# Generated by Django 5.0.6 on 2024-07-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_constructioncompany_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='auther',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='auther',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='auther',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
